name: Flask CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-test

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run:  |
        pip install -r requirements.txt
    
    - name: Run tests
      run:  |
        pytest
